require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AvaluosController do

  # This should return the minimal set of attributes required to create a valid
  # Avaluo. As you add validations to Avaluo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all avaluos as @avaluos" do
      avaluo = Avaluo.create! valid_attributes
      get :index
      assigns(:avaluos).should eq([avaluo])
    end
  end

  describe "GET show" do
    it "assigns the requested avaluo as @avaluo" do
      avaluo = Avaluo.create! valid_attributes
      get :show, :id => avaluo.id.to_s
      assigns(:avaluo).should eq(avaluo)
    end
  end

  describe "GET new" do
    it "assigns a new avaluo as @avaluo" do
      get :new
      assigns(:avaluo).should be_a_new(Avaluo)
    end
  end

  describe "GET edit" do
    it "assigns the requested avaluo as @avaluo" do
      avaluo = Avaluo.create! valid_attributes
      get :edit, :id => avaluo.id.to_s
      assigns(:avaluo).should eq(avaluo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Avaluo" do
        expect {
          post :create, :avaluo => valid_attributes
        }.to change(Avaluo, :count).by(1)
      end

      it "assigns a newly created avaluo as @avaluo" do
        post :create, :avaluo => valid_attributes
        assigns(:avaluo).should be_a(Avaluo)
        assigns(:avaluo).should be_persisted
      end

      it "redirects to the created avaluo" do
        post :create, :avaluo => valid_attributes
        response.should redirect_to(Avaluo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved avaluo as @avaluo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Avaluo.any_instance.stub(:save).and_return(false)
        post :create, :avaluo => {}
        assigns(:avaluo).should be_a_new(Avaluo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Avaluo.any_instance.stub(:save).and_return(false)
        post :create, :avaluo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested avaluo" do
        avaluo = Avaluo.create! valid_attributes
        # Assuming there are no other avaluos in the database, this
        # specifies that the Avaluo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Avaluo.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => avaluo.id, :avaluo => {'these' => 'params'}
      end

      it "assigns the requested avaluo as @avaluo" do
        avaluo = Avaluo.create! valid_attributes
        put :update, :id => avaluo.id, :avaluo => valid_attributes
        assigns(:avaluo).should eq(avaluo)
      end

      it "redirects to the avaluo" do
        avaluo = Avaluo.create! valid_attributes
        put :update, :id => avaluo.id, :avaluo => valid_attributes
        response.should redirect_to(avaluo)
      end
    end

    describe "with invalid params" do
      it "assigns the avaluo as @avaluo" do
        avaluo = Avaluo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Avaluo.any_instance.stub(:save).and_return(false)
        put :update, :id => avaluo.id.to_s, :avaluo => {}
        assigns(:avaluo).should eq(avaluo)
      end

      it "re-renders the 'edit' template" do
        avaluo = Avaluo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Avaluo.any_instance.stub(:save).and_return(false)
        put :update, :id => avaluo.id.to_s, :avaluo => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested avaluo" do
      avaluo = Avaluo.create! valid_attributes
      expect {
        delete :destroy, :id => avaluo.id.to_s
      }.to change(Avaluo, :count).by(-1)
    end

    it "redirects to the avaluos list" do
      avaluo = Avaluo.create! valid_attributes
      delete :destroy, :id => avaluo.id.to_s
      response.should redirect_to(avaluos_url)
    end
  end

end
