require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CivilsController do

  # This should return the minimal set of attributes required to create a valid
  # Civil. As you add validations to Civil, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all civils as @civils" do
      civil = Civil.create! valid_attributes
      get :index
      assigns(:civils).should eq([civil])
    end
  end

  describe "GET show" do
    it "assigns the requested civil as @civil" do
      civil = Civil.create! valid_attributes
      get :show, :id => civil.id.to_s
      assigns(:civil).should eq(civil)
    end
  end

  describe "GET new" do
    it "assigns a new civil as @civil" do
      get :new
      assigns(:civil).should be_a_new(Civil)
    end
  end

  describe "GET edit" do
    it "assigns the requested civil as @civil" do
      civil = Civil.create! valid_attributes
      get :edit, :id => civil.id.to_s
      assigns(:civil).should eq(civil)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Civil" do
        expect {
          post :create, :civil => valid_attributes
        }.to change(Civil, :count).by(1)
      end

      it "assigns a newly created civil as @civil" do
        post :create, :civil => valid_attributes
        assigns(:civil).should be_a(Civil)
        assigns(:civil).should be_persisted
      end

      it "redirects to the created civil" do
        post :create, :civil => valid_attributes
        response.should redirect_to(Civil.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved civil as @civil" do
        # Trigger the behavior that occurs when invalid params are submitted
        Civil.any_instance.stub(:save).and_return(false)
        post :create, :civil => {}
        assigns(:civil).should be_a_new(Civil)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Civil.any_instance.stub(:save).and_return(false)
        post :create, :civil => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested civil" do
        civil = Civil.create! valid_attributes
        # Assuming there are no other civils in the database, this
        # specifies that the Civil created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Civil.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => civil.id, :civil => {'these' => 'params'}
      end

      it "assigns the requested civil as @civil" do
        civil = Civil.create! valid_attributes
        put :update, :id => civil.id, :civil => valid_attributes
        assigns(:civil).should eq(civil)
      end

      it "redirects to the civil" do
        civil = Civil.create! valid_attributes
        put :update, :id => civil.id, :civil => valid_attributes
        response.should redirect_to(civil)
      end
    end

    describe "with invalid params" do
      it "assigns the civil as @civil" do
        civil = Civil.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Civil.any_instance.stub(:save).and_return(false)
        put :update, :id => civil.id.to_s, :civil => {}
        assigns(:civil).should eq(civil)
      end

      it "re-renders the 'edit' template" do
        civil = Civil.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Civil.any_instance.stub(:save).and_return(false)
        put :update, :id => civil.id.to_s, :civil => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested civil" do
      civil = Civil.create! valid_attributes
      expect {
        delete :destroy, :id => civil.id.to_s
      }.to change(Civil, :count).by(-1)
    end

    it "redirects to the civils list" do
      civil = Civil.create! valid_attributes
      delete :destroy, :id => civil.id.to_s
      response.should redirect_to(civils_url)
    end
  end

end
