require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DebtsController do

  # This should return the minimal set of attributes required to create a valid
  # Debt. As you add validations to Debt, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all debts as @debts" do
      debt = Debt.create! valid_attributes
      get :index
      assigns(:debts).should eq([debt])
    end
  end

  describe "GET show" do
    it "assigns the requested debt as @debt" do
      debt = Debt.create! valid_attributes
      get :show, :id => debt.id.to_s
      assigns(:debt).should eq(debt)
    end
  end

  describe "GET new" do
    it "assigns a new debt as @debt" do
      get :new
      assigns(:debt).should be_a_new(Debt)
    end
  end

  describe "GET edit" do
    it "assigns the requested debt as @debt" do
      debt = Debt.create! valid_attributes
      get :edit, :id => debt.id.to_s
      assigns(:debt).should eq(debt)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Debt" do
        expect {
          post :create, :debt => valid_attributes
        }.to change(Debt, :count).by(1)
      end

      it "assigns a newly created debt as @debt" do
        post :create, :debt => valid_attributes
        assigns(:debt).should be_a(Debt)
        assigns(:debt).should be_persisted
      end

      it "redirects to the created debt" do
        post :create, :debt => valid_attributes
        response.should redirect_to(Debt.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved debt as @debt" do
        # Trigger the behavior that occurs when invalid params are submitted
        Debt.any_instance.stub(:save).and_return(false)
        post :create, :debt => {}
        assigns(:debt).should be_a_new(Debt)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Debt.any_instance.stub(:save).and_return(false)
        post :create, :debt => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested debt" do
        debt = Debt.create! valid_attributes
        # Assuming there are no other debts in the database, this
        # specifies that the Debt created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Debt.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => debt.id, :debt => {'these' => 'params'}
      end

      it "assigns the requested debt as @debt" do
        debt = Debt.create! valid_attributes
        put :update, :id => debt.id, :debt => valid_attributes
        assigns(:debt).should eq(debt)
      end

      it "redirects to the debt" do
        debt = Debt.create! valid_attributes
        put :update, :id => debt.id, :debt => valid_attributes
        response.should redirect_to(debt)
      end
    end

    describe "with invalid params" do
      it "assigns the debt as @debt" do
        debt = Debt.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Debt.any_instance.stub(:save).and_return(false)
        put :update, :id => debt.id.to_s, :debt => {}
        assigns(:debt).should eq(debt)
      end

      it "re-renders the 'edit' template" do
        debt = Debt.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Debt.any_instance.stub(:save).and_return(false)
        put :update, :id => debt.id.to_s, :debt => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested debt" do
      debt = Debt.create! valid_attributes
      expect {
        delete :destroy, :id => debt.id.to_s
      }.to change(Debt, :count).by(-1)
    end

    it "redirects to the debts list" do
      debt = Debt.create! valid_attributes
      delete :destroy, :id => debt.id.to_s
      response.should redirect_to(debts_url)
    end
  end

end
