require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LotesController do

  # This should return the minimal set of attributes required to create a valid
  # Lote. As you add validations to Lote, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all lotes as @lotes" do
      lote = Lote.create! valid_attributes
      get :index
      assigns(:lotes).should eq([lote])
    end
  end

  describe "GET show" do
    it "assigns the requested lote as @lote" do
      lote = Lote.create! valid_attributes
      get :show, :id => lote.id.to_s
      assigns(:lote).should eq(lote)
    end
  end

  describe "GET new" do
    it "assigns a new lote as @lote" do
      get :new
      assigns(:lote).should be_a_new(Lote)
    end
  end

  describe "GET edit" do
    it "assigns the requested lote as @lote" do
      lote = Lote.create! valid_attributes
      get :edit, :id => lote.id.to_s
      assigns(:lote).should eq(lote)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lote" do
        expect {
          post :create, :lote => valid_attributes
        }.to change(Lote, :count).by(1)
      end

      it "assigns a newly created lote as @lote" do
        post :create, :lote => valid_attributes
        assigns(:lote).should be_a(Lote)
        assigns(:lote).should be_persisted
      end

      it "redirects to the created lote" do
        post :create, :lote => valid_attributes
        response.should redirect_to(Lote.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lote as @lote" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lote.any_instance.stub(:save).and_return(false)
        post :create, :lote => {}
        assigns(:lote).should be_a_new(Lote)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lote.any_instance.stub(:save).and_return(false)
        post :create, :lote => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lote" do
        lote = Lote.create! valid_attributes
        # Assuming there are no other lotes in the database, this
        # specifies that the Lote created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lote.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => lote.id, :lote => {'these' => 'params'}
      end

      it "assigns the requested lote as @lote" do
        lote = Lote.create! valid_attributes
        put :update, :id => lote.id, :lote => valid_attributes
        assigns(:lote).should eq(lote)
      end

      it "redirects to the lote" do
        lote = Lote.create! valid_attributes
        put :update, :id => lote.id, :lote => valid_attributes
        response.should redirect_to(lote)
      end
    end

    describe "with invalid params" do
      it "assigns the lote as @lote" do
        lote = Lote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lote.any_instance.stub(:save).and_return(false)
        put :update, :id => lote.id.to_s, :lote => {}
        assigns(:lote).should eq(lote)
      end

      it "re-renders the 'edit' template" do
        lote = Lote.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lote.any_instance.stub(:save).and_return(false)
        put :update, :id => lote.id.to_s, :lote => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lote" do
      lote = Lote.create! valid_attributes
      expect {
        delete :destroy, :id => lote.id.to_s
      }.to change(Lote, :count).by(-1)
    end

    it "redirects to the lotes list" do
      lote = Lote.create! valid_attributes
      delete :destroy, :id => lote.id.to_s
      response.should redirect_to(lotes_url)
    end
  end

end
