require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NacionalidadsController do

  # This should return the minimal set of attributes required to create a valid
  # Nacionalidad. As you add validations to Nacionalidad, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all nacionalidads as @nacionalidads" do
      nacionalidad = Nacionalidad.create! valid_attributes
      get :index
      assigns(:nacionalidads).should eq([nacionalidad])
    end
  end

  describe "GET show" do
    it "assigns the requested nacionalidad as @nacionalidad" do
      nacionalidad = Nacionalidad.create! valid_attributes
      get :show, :id => nacionalidad.id.to_s
      assigns(:nacionalidad).should eq(nacionalidad)
    end
  end

  describe "GET new" do
    it "assigns a new nacionalidad as @nacionalidad" do
      get :new
      assigns(:nacionalidad).should be_a_new(Nacionalidad)
    end
  end

  describe "GET edit" do
    it "assigns the requested nacionalidad as @nacionalidad" do
      nacionalidad = Nacionalidad.create! valid_attributes
      get :edit, :id => nacionalidad.id.to_s
      assigns(:nacionalidad).should eq(nacionalidad)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Nacionalidad" do
        expect {
          post :create, :nacionalidad => valid_attributes
        }.to change(Nacionalidad, :count).by(1)
      end

      it "assigns a newly created nacionalidad as @nacionalidad" do
        post :create, :nacionalidad => valid_attributes
        assigns(:nacionalidad).should be_a(Nacionalidad)
        assigns(:nacionalidad).should be_persisted
      end

      it "redirects to the created nacionalidad" do
        post :create, :nacionalidad => valid_attributes
        response.should redirect_to(Nacionalidad.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nacionalidad as @nacionalidad" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nacionalidad.any_instance.stub(:save).and_return(false)
        post :create, :nacionalidad => {}
        assigns(:nacionalidad).should be_a_new(Nacionalidad)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Nacionalidad.any_instance.stub(:save).and_return(false)
        post :create, :nacionalidad => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nacionalidad" do
        nacionalidad = Nacionalidad.create! valid_attributes
        # Assuming there are no other nacionalidads in the database, this
        # specifies that the Nacionalidad created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Nacionalidad.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => nacionalidad.id, :nacionalidad => {'these' => 'params'}
      end

      it "assigns the requested nacionalidad as @nacionalidad" do
        nacionalidad = Nacionalidad.create! valid_attributes
        put :update, :id => nacionalidad.id, :nacionalidad => valid_attributes
        assigns(:nacionalidad).should eq(nacionalidad)
      end

      it "redirects to the nacionalidad" do
        nacionalidad = Nacionalidad.create! valid_attributes
        put :update, :id => nacionalidad.id, :nacionalidad => valid_attributes
        response.should redirect_to(nacionalidad)
      end
    end

    describe "with invalid params" do
      it "assigns the nacionalidad as @nacionalidad" do
        nacionalidad = Nacionalidad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nacionalidad.any_instance.stub(:save).and_return(false)
        put :update, :id => nacionalidad.id.to_s, :nacionalidad => {}
        assigns(:nacionalidad).should eq(nacionalidad)
      end

      it "re-renders the 'edit' template" do
        nacionalidad = Nacionalidad.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Nacionalidad.any_instance.stub(:save).and_return(false)
        put :update, :id => nacionalidad.id.to_s, :nacionalidad => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nacionalidad" do
      nacionalidad = Nacionalidad.create! valid_attributes
      expect {
        delete :destroy, :id => nacionalidad.id.to_s
      }.to change(Nacionalidad, :count).by(-1)
    end

    it "redirects to the nacionalidads list" do
      nacionalidad = Nacionalidad.create! valid_attributes
      delete :destroy, :id => nacionalidad.id.to_s
      response.should redirect_to(nacionalidads_url)
    end
  end

end
