require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaysController do

  # This should return the minimal set of attributes required to create a valid
  # Pay. As you add validations to Pay, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all pays as @pays" do
      pay = Pay.create! valid_attributes
      get :index
      assigns(:pays).should eq([pay])
    end
  end

  describe "GET show" do
    it "assigns the requested pay as @pay" do
      pay = Pay.create! valid_attributes
      get :show, :id => pay.id.to_s
      assigns(:pay).should eq(pay)
    end
  end

  describe "GET new" do
    it "assigns a new pay as @pay" do
      get :new
      assigns(:pay).should be_a_new(Pay)
    end
  end

  describe "GET edit" do
    it "assigns the requested pay as @pay" do
      pay = Pay.create! valid_attributes
      get :edit, :id => pay.id.to_s
      assigns(:pay).should eq(pay)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pay" do
        expect {
          post :create, :pay => valid_attributes
        }.to change(Pay, :count).by(1)
      end

      it "assigns a newly created pay as @pay" do
        post :create, :pay => valid_attributes
        assigns(:pay).should be_a(Pay)
        assigns(:pay).should be_persisted
      end

      it "redirects to the created pay" do
        post :create, :pay => valid_attributes
        response.should redirect_to(Pay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pay as @pay" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pay.any_instance.stub(:save).and_return(false)
        post :create, :pay => {}
        assigns(:pay).should be_a_new(Pay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pay.any_instance.stub(:save).and_return(false)
        post :create, :pay => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pay" do
        pay = Pay.create! valid_attributes
        # Assuming there are no other pays in the database, this
        # specifies that the Pay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pay.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => pay.id, :pay => {'these' => 'params'}
      end

      it "assigns the requested pay as @pay" do
        pay = Pay.create! valid_attributes
        put :update, :id => pay.id, :pay => valid_attributes
        assigns(:pay).should eq(pay)
      end

      it "redirects to the pay" do
        pay = Pay.create! valid_attributes
        put :update, :id => pay.id, :pay => valid_attributes
        response.should redirect_to(pay)
      end
    end

    describe "with invalid params" do
      it "assigns the pay as @pay" do
        pay = Pay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pay.any_instance.stub(:save).and_return(false)
        put :update, :id => pay.id.to_s, :pay => {}
        assigns(:pay).should eq(pay)
      end

      it "re-renders the 'edit' template" do
        pay = Pay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pay.any_instance.stub(:save).and_return(false)
        put :update, :id => pay.id.to_s, :pay => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pay" do
      pay = Pay.create! valid_attributes
      expect {
        delete :destroy, :id => pay.id.to_s
      }.to change(Pay, :count).by(-1)
    end

    it "redirects to the pays list" do
      pay = Pay.create! valid_attributes
      delete :destroy, :id => pay.id.to_s
      response.should redirect_to(pays_url)
    end
  end

end
