require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaddressesController do

  # This should return the minimal set of attributes required to create a valid
  # Taddress. As you add validations to Taddress, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all taddresses as @taddresses" do
      taddress = Taddress.create! valid_attributes
      get :index
      assigns(:taddresses).should eq([taddress])
    end
  end

  describe "GET show" do
    it "assigns the requested taddress as @taddress" do
      taddress = Taddress.create! valid_attributes
      get :show, :id => taddress.id.to_s
      assigns(:taddress).should eq(taddress)
    end
  end

  describe "GET new" do
    it "assigns a new taddress as @taddress" do
      get :new
      assigns(:taddress).should be_a_new(Taddress)
    end
  end

  describe "GET edit" do
    it "assigns the requested taddress as @taddress" do
      taddress = Taddress.create! valid_attributes
      get :edit, :id => taddress.id.to_s
      assigns(:taddress).should eq(taddress)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Taddress" do
        expect {
          post :create, :taddress => valid_attributes
        }.to change(Taddress, :count).by(1)
      end

      it "assigns a newly created taddress as @taddress" do
        post :create, :taddress => valid_attributes
        assigns(:taddress).should be_a(Taddress)
        assigns(:taddress).should be_persisted
      end

      it "redirects to the created taddress" do
        post :create, :taddress => valid_attributes
        response.should redirect_to(Taddress.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved taddress as @taddress" do
        # Trigger the behavior that occurs when invalid params are submitted
        Taddress.any_instance.stub(:save).and_return(false)
        post :create, :taddress => {}
        assigns(:taddress).should be_a_new(Taddress)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Taddress.any_instance.stub(:save).and_return(false)
        post :create, :taddress => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested taddress" do
        taddress = Taddress.create! valid_attributes
        # Assuming there are no other taddresses in the database, this
        # specifies that the Taddress created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Taddress.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => taddress.id, :taddress => {'these' => 'params'}
      end

      it "assigns the requested taddress as @taddress" do
        taddress = Taddress.create! valid_attributes
        put :update, :id => taddress.id, :taddress => valid_attributes
        assigns(:taddress).should eq(taddress)
      end

      it "redirects to the taddress" do
        taddress = Taddress.create! valid_attributes
        put :update, :id => taddress.id, :taddress => valid_attributes
        response.should redirect_to(taddress)
      end
    end

    describe "with invalid params" do
      it "assigns the taddress as @taddress" do
        taddress = Taddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Taddress.any_instance.stub(:save).and_return(false)
        put :update, :id => taddress.id.to_s, :taddress => {}
        assigns(:taddress).should eq(taddress)
      end

      it "re-renders the 'edit' template" do
        taddress = Taddress.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Taddress.any_instance.stub(:save).and_return(false)
        put :update, :id => taddress.id.to_s, :taddress => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested taddress" do
      taddress = Taddress.create! valid_attributes
      expect {
        delete :destroy, :id => taddress.id.to_s
      }.to change(Taddress, :count).by(-1)
    end

    it "redirects to the taddresses list" do
      taddress = Taddress.create! valid_attributes
      delete :destroy, :id => taddress.id.to_s
      response.should redirect_to(taddresses_url)
    end
  end

end
