require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TdocsController do

  # This should return the minimal set of attributes required to create a valid
  # Tdoc. As you add validations to Tdoc, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all tdocs as @tdocs" do
      tdoc = Tdoc.create! valid_attributes
      get :index
      assigns(:tdocs).should eq([tdoc])
    end
  end

  describe "GET show" do
    it "assigns the requested tdoc as @tdoc" do
      tdoc = Tdoc.create! valid_attributes
      get :show, :id => tdoc.id.to_s
      assigns(:tdoc).should eq(tdoc)
    end
  end

  describe "GET new" do
    it "assigns a new tdoc as @tdoc" do
      get :new
      assigns(:tdoc).should be_a_new(Tdoc)
    end
  end

  describe "GET edit" do
    it "assigns the requested tdoc as @tdoc" do
      tdoc = Tdoc.create! valid_attributes
      get :edit, :id => tdoc.id.to_s
      assigns(:tdoc).should eq(tdoc)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tdoc" do
        expect {
          post :create, :tdoc => valid_attributes
        }.to change(Tdoc, :count).by(1)
      end

      it "assigns a newly created tdoc as @tdoc" do
        post :create, :tdoc => valid_attributes
        assigns(:tdoc).should be_a(Tdoc)
        assigns(:tdoc).should be_persisted
      end

      it "redirects to the created tdoc" do
        post :create, :tdoc => valid_attributes
        response.should redirect_to(Tdoc.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tdoc as @tdoc" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tdoc.any_instance.stub(:save).and_return(false)
        post :create, :tdoc => {}
        assigns(:tdoc).should be_a_new(Tdoc)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tdoc.any_instance.stub(:save).and_return(false)
        post :create, :tdoc => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tdoc" do
        tdoc = Tdoc.create! valid_attributes
        # Assuming there are no other tdocs in the database, this
        # specifies that the Tdoc created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tdoc.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => tdoc.id, :tdoc => {'these' => 'params'}
      end

      it "assigns the requested tdoc as @tdoc" do
        tdoc = Tdoc.create! valid_attributes
        put :update, :id => tdoc.id, :tdoc => valid_attributes
        assigns(:tdoc).should eq(tdoc)
      end

      it "redirects to the tdoc" do
        tdoc = Tdoc.create! valid_attributes
        put :update, :id => tdoc.id, :tdoc => valid_attributes
        response.should redirect_to(tdoc)
      end
    end

    describe "with invalid params" do
      it "assigns the tdoc as @tdoc" do
        tdoc = Tdoc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tdoc.any_instance.stub(:save).and_return(false)
        put :update, :id => tdoc.id.to_s, :tdoc => {}
        assigns(:tdoc).should eq(tdoc)
      end

      it "re-renders the 'edit' template" do
        tdoc = Tdoc.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tdoc.any_instance.stub(:save).and_return(false)
        put :update, :id => tdoc.id.to_s, :tdoc => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tdoc" do
      tdoc = Tdoc.create! valid_attributes
      expect {
        delete :destroy, :id => tdoc.id.to_s
      }.to change(Tdoc, :count).by(-1)
    end

    it "redirects to the tdocs list" do
      tdoc = Tdoc.create! valid_attributes
      delete :destroy, :id => tdoc.id.to_s
      response.should redirect_to(tdocs_url)
    end
  end

end
